export const USER_SEARCH_DEBOUNCE_MS = 300;
export const JWT_EXPIRY_SKEW_SECONDS = 5;
export const SECONDS_TO_MILLISECONDS = 1000;
export const MINUTES_TO_MILLISECONDS = 60 * SECONDS_TO_MILLISECONDS;
